/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlbumsSlugRouteImport } from './routes/albums.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminUploadRouteImport } from './routes/_authenticated.admin.upload'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminAlbumsIndexRouteImport } from './routes/_authenticated.admin.albums.index'
import { Route as AuthenticatedAdminAlbumsIdRouteImport } from './routes/_authenticated.admin.albums.$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugRoute = AlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUploadRoute =
  AuthenticatedAdminUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlbumsIndexRoute =
  AuthenticatedAdminAlbumsIndexRouteImport.update({
    id: '/albums/',
    path: '/albums/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlbumsIdRoute =
  AuthenticatedAdminAlbumsIdRouteImport.update({
    id: '/albums/$id',
    path: '/albums/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/albums/$id': typeof AuthenticatedAdminAlbumsIdRoute
  '/admin/albums/': typeof AuthenticatedAdminAlbumsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/albums/$id': typeof AuthenticatedAdminAlbumsIdRoute
  '/admin/albums': typeof AuthenticatedAdminAlbumsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/upload': typeof AuthenticatedAdminUploadRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/albums/$id': typeof AuthenticatedAdminAlbumsIdRoute
  '/_authenticated/admin/albums/': typeof AuthenticatedAdminAlbumsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/albums/$slug'
    | '/admin/settings'
    | '/admin/upload'
    | '/admin/'
    | '/admin/albums/$id'
    | '/admin/albums/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/albums/$slug'
    | '/admin/settings'
    | '/admin/upload'
    | '/admin'
    | '/admin/albums/$id'
    | '/admin/albums'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/admin/login'
    | '/albums/$slug'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/upload'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/albums/$id'
    | '/_authenticated/admin/albums/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AlbumsSlugRoute: typeof AlbumsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug': {
      id: '/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/albums/$slug'
      preLoaderRoute: typeof AlbumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/upload': {
      id: '/_authenticated/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AuthenticatedAdminUploadRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/albums/': {
      id: '/_authenticated/admin/albums/'
      path: '/albums'
      fullPath: '/admin/albums/'
      preLoaderRoute: typeof AuthenticatedAdminAlbumsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/albums/$id': {
      id: '/_authenticated/admin/albums/$id'
      path: '/albums/$id'
      fullPath: '/admin/albums/$id'
      preLoaderRoute: typeof AuthenticatedAdminAlbumsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUploadRoute: typeof AuthenticatedAdminUploadRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAlbumsIdRoute: typeof AuthenticatedAdminAlbumsIdRoute
  AuthenticatedAdminAlbumsIndexRoute: typeof AuthenticatedAdminAlbumsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUploadRoute: AuthenticatedAdminUploadRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminAlbumsIdRoute: AuthenticatedAdminAlbumsIdRoute,
  AuthenticatedAdminAlbumsIndexRoute: AuthenticatedAdminAlbumsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AlbumsSlugRoute: AlbumsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
